#!/bin/sh

#!/bin/sh

if [[ $EUID -eq 0 ]]; then
    echo "This script must be NOT run as root" 1>&2
    exit 1
fi


cd $HOME

mkdir -pv $HOME/.config/openbox $HOME/.config/polybar $HOME/Documents

cp -r /usr/local/share/openbox/* $HOME/.config/openbox/
cp -r /usr/local/share/polybar/* $HOME/.config/polybar/

if ! grep openbox $HOME/.bashrc ;then
    echo "export XSESSION=openbox" >>  $HOME/.bashrc 
fi